
  CREATE TABLE "VASAPPS"."IGM_MARKS_NUMBER_DESCRIPTION_TWO" 
   (	"PK_BL_NO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"MARKS_NUMBER" VARCHAR2(4000 BYTE), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"REMARK" VARCHAR2(4000 BYTE), 
	 PRIMARY KEY ("PK_BL_NO") DISABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VASDATA" ;
