
  CREATE TABLE "VASAPPS"."IGM_PERSON_ON_BOARD" 
   (	"BL_NO_PK" VARCHAR2(20 BYTE), 
	"TYPE_CODE" VARCHAR2(3 BYTE), 
	"FAMILY_NAME" VARCHAR2(70 BYTE), 
	"GIVEN_NAME" VARCHAR2(20 BYTE), 
	"NATIONALITY_CODE" VARCHAR2(2 BYTE), 
	"INTRANSIT_INDICATOR" VARCHAR2(1 BYTE), 
	"CREW_MEMBER_RANKOR_RATING" VARCHAR2(70 BYTE), 
	"CREW_MEMBER_RANKORRATING_CODE" VARCHAR2(70 BYTE), 
	"PORTOFEMBARKATIONCODE" VARCHAR2(5 BYTE), 
	"PORT_OF_EMBARKATION_NAME" VARCHAR2(256 BYTE), 
	"PORT_OF_DISEMBARKATION_CODE" VARCHAR2(5 BYTE), 
	"PORT_OF_DISEMBARKATION_NAME" VARCHAR2(256 BYTE), 
	"GENDER_CODE" VARCHAR2(3 BYTE), 
	"DATE_OF_BIRTH" VARCHAR2(20 BYTE), 
	"PLACE_OF_BIRTHNAME" VARCHAR2(35 BYTE), 
	"COUNTRY_OF_BIRTH_CODE" VARCHAR2(2 BYTE), 
	"IDENTITY_DOC_EXPIRY_DATE" VARCHAR2(20 BYTE), 
	"IDENTITY_OR_TRAVEL_DOC_ISSUING_NATION_CODE" VARCHAR2(3 BYTE), 
	"IDENTITY_OR_TRAVEL_DOC_NMBR" VARCHAR2(30 BYTE), 
	"IDENTITY_OR_TRAVEL_DOC_TYPE_CODE" VARCHAR2(3 BYTE), 
	"VISA" VARCHAR2(70 BYTE), 
	"PNR_NUMBER" VARCHAR2(20 BYTE), 
	"VESSEL" VARCHAR2(20 BYTE), 
	"VOYAGE" VARCHAR2(20 BYTE), 
	"POD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VASDATA" ;
