
  CREATE TABLE "VASAPPS"."IGM_CREW_EFFECT_FORMATE" 
   (	"BL_NO_PK" VARCHAR2(20 BYTE), 
	"DESCRIPTION_CODE" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(70 BYTE), 
	"QUANTITY_ON_BOARD" VARCHAR2(70 BYTE), 
	"QUANTITY_ON_BOARD_CODE" VARCHAR2(20 BYTE), 
	"VESSEL_SRNO" VARCHAR2(20 BYTE), 
	"VESSEL" VARCHAR2(20 BYTE), 
	"VOYAGE" VARCHAR2(20 BYTE), 
	"POD" VARCHAR2(20 BYTE), 
	"SEQUENCE_NO" VARCHAR2(20 BYTE), 
	"PERSON_ON_BOARD_SEQUENCE_NO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VASDATA" ;
