
  CREATE TABLE "VASAPPS"."DEX_BL_CONTAINERS_TEMP" 
   (	"MBL_NO" VARCHAR2(30 CHAR), 
	"NET_MSMT_METRIC" NUMBER(30,20), 
	"METRIC_MSMT" NUMBER(30,20), 
	 PRIMARY KEY ("MBL_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VASDATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VASDATA" ;


  GRANT SELECT ON "VASAPPS"."DEX_BL_CONTAINERS_TEMP" TO "VASAPPS_RO";
  GRANT DELETE ON "VASAPPS"."DEX_BL_CONTAINERS_TEMP" TO "VASAPPS_RW";
  GRANT INSERT ON "VASAPPS"."DEX_BL_CONTAINERS_TEMP" TO "VASAPPS_RW";
  GRANT SELECT ON "VASAPPS"."DEX_BL_CONTAINERS_TEMP" TO "VASAPPS_RW";
  GRANT UPDATE ON "VASAPPS"."DEX_BL_CONTAINERS_TEMP" TO "VASAPPS_RW";
  GRANT DELETE ON "VASAPPS"."DEX_BL_CONTAINERS_TEMP" TO "EDWAPPS";
  GRANT INSERT ON "VASAPPS"."DEX_BL_CONTAINERS_TEMP" TO "EDWAPPS";
  GRANT SELECT ON "VASAPPS"."DEX_BL_CONTAINERS_TEMP" TO "EDWAPPS";
  GRANT UPDATE ON "VASAPPS"."DEX_BL_CONTAINERS_TEMP" TO "EDWAPPS";
