
  CREATE TABLE "VASAPPS"."IGM_CONTAINER_DETAILS_TWO" 
   (	"PK_BL_NO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DN_CONTAINER_NO" VARCHAR2(12 BYTE) NOT NULL ENABLE, 
	"CUSTOMER_SEAL_NO" VARCHAR2(20 BYTE), 
	"EQUIPMENT_STATUS" VARCHAR2(5 BYTE), 
	"QTY_PACKAGES" VARCHAR2(6 BYTE), 
	"METRIC_WEIGHT" VARCHAR2(20 BYTE), 
	"DN_EQ_SIZE" VARCHAR2(2 BYTE), 
	"DN_EQ_TYPE" VARCHAR2(10 BYTE), 
	"CONTAINER_BONDFLAG" VARCHAR2(1 BYTE), 
	"EQUIPMENT_LOAD_STATUS" VARCHAR2(3 BYTE), 
	"SOC_FLAG" VARCHAR2(5 BYTE), 
	"EQUIPMENT_SEAL_TYPE" VARCHAR2(255 BYTE), 
	"CONTAINER_AGENT" VARCHAR2(50 BYTE), 
	"CBM" VARCHAR2(50 BYTE), 
	"ISO_CODE" VARCHAR2(50 BYTE), 
	"UNOS" VARCHAR2(50 BYTE), 
	"IMO" VARCHAR2(50 BYTE), 
	"REMARKS" VARCHAR2(500 BYTE), 
	"CLASSIFICATION" VARCHAR2(500 BYTE), 
	"TYPE_DETAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VASDATA" ;
