
  CREATE TABLE "VASAPPS"."IGM_NODIFY_PARTY_IGM_TWO" 
   (	"PK_BL_NO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CUSTOMER_CODE" VARCHAR2(10 BYTE), 
	"CUSTOMER_NAME" VARCHAR2(112 BYTE), 
	"ADDRESS_LINE_1" VARCHAR2(35 BYTE), 
	"ADDRESS_LINE_2" VARCHAR2(35 BYTE), 
	"ADDRESS_LINE_3" VARCHAR2(35 BYTE), 
	"ADDRESS_LINE_4" VARCHAR2(35 BYTE), 
	"CITY" VARCHAR2(25 BYTE), 
	"STATE" VARCHAR2(2 BYTE), 
	"DN_COUNTRY_CODE" VARCHAR2(2 BYTE), 
	"ZIP" VARCHAR2(15 BYTE), 
	"NOTIFY2" VARCHAR2(225 BYTE), 
	 PRIMARY KEY ("PK_BL_NO") DISABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VASDATA" ;
