
  CREATE TABLE "VASAPPS"."IGM_HBL_DETAILS" 
   (	"MBL_NO_FK" VARCHAR2(20 BYTE), 
	"HBL_NO_PK" VARCHAR2(20 BYTE), 
	"SERVICE" VARCHAR2(20 BYTE), 
	"VESSEL" VARCHAR2(20 BYTE), 
	"VOYAGE" VARCHAR2(20 BYTE), 
	"POL_TERMINAL" VARCHAR2(20 BYTE), 
	"POD" VARCHAR2(20 BYTE), 
	"CONSOLIDATED_INDICATOR" VARCHAR2(1 BYTE), 
	"PREVIOUS_DECLARATION" VARCHAR2(1 BYTE), 
	"CONSOLIDATOR_PAN" VARCHAR2(16 BYTE), 
	"CIN_TYPE" VARCHAR2(4 BYTE), 
	"MCIN" VARCHAR2(20 BYTE), 
	"CSN_SUBMITTED_TYPE" VARCHAR2(4 BYTE), 
	"CSN_SUBMITTED_BY" VARCHAR2(20 BYTE), 
	"CSN_REPORTING_TYPE" VARCHAR2(4 BYTE), 
	"CSN_SITE_ID" VARCHAR2(4 BYTE), 
	"CSN_NUMBER" VARCHAR2(7 BYTE), 
	"CSN_DATE" VARCHAR2(8 BYTE), 
	"PREVIOUS_MCIN" VARCHAR2(20 BYTE), 
	"SPLIT_INDICATOR" VARCHAR2(2 BYTE), 
	"NUMBER_OF_PACKAGES" VARCHAR2(6 BYTE), 
	"TYPE_OF_PACKAGE" VARCHAR2(35 BYTE), 
	"FIRST_PORT_OF_ENTRY_LAST_PORT_OF_DEPARTURE" VARCHAR2(100 BYTE), 
	"TYPE_OF_CARGO" VARCHAR2(20 BYTE), 
	"SPLIT_INDICATOR_LIST" VARCHAR2(1 BYTE), 
	"PORT_OF_ACCEPTANCE" VARCHAR2(5 BYTE), 
	"PORT_OF_RECEIPT" VARCHAR2(6 BYTE), 
	"UCR_TYPE" VARCHAR2(20 BYTE), 
	"UCR_CODE" VARCHAR2(35 BYTE), 
	"PORT_OF_ACCEPTANCE_NAME" VARCHAR2(100 BYTE), 
	"PORT_OF_RECEIPT_NAME" VARCHAR2(256 BYTE), 
	"PAN_OF_NOTIFIED_PARTY" VARCHAR2(30 BYTE), 
	"UNIT_OF_WEIGHT" VARCHAR2(20 BYTE), 
	"GROSS_VOLUME" VARCHAR2(100 BYTE), 
	"UNIT_OF_VOLUME" VARCHAR2(100 BYTE), 
	"CARGO_ITEM_SEQUENCE_NO" VARCHAR2(100 BYTE), 
	"CARGO_ITEM_DESCRIPTION" VARCHAR2(200 BYTE), 
	"CONTAINER_WEIGHT" VARCHAR2(6 BYTE), 
	"NUMBER_OF_PACKAGES_HID" VARCHAR2(6 BYTE), 
	"TYPE_OF_PACKAGES_HID" VARCHAR2(35 BYTE), 
	"PORT_OF_CALL_SEQUENCE_NUMBER" VARCHAR2(100 BYTE), 
	"PORT_OF_CALL_CODED" VARCHAR2(100 BYTE), 
	"NEXT_PORT_OF_CALL_CODED" VARCHAR2(100 BYTE), 
	"MC_LOCATION_CUSTOMS" VARCHAR2(20 BYTE), 
	"UNO_CODE" VARCHAR2(5 BYTE), 
	"IMDG_CODE" VARCHAR2(4 BYTE), 
	"BL_DATE" VARCHAR2(20 BYTE), 
	"BL_VERSION" VARCHAR2(20 BYTE), 
	"DEL_VLS" VARCHAR2(20 BYTE), 
	"DEPOT_VLS" VARCHAR2(20 BYTE), 
	"ENBLOCK_MOVEMENT" VARCHAR2(20 BYTE), 
	"CARRIER_NO" VARCHAR2(20 BYTE), 
	"AGENCY_TYPE" VARCHAR2(20 BYTE), 
	"INVOICE_VALUE_FC" VARCHAR2(20 BYTE), 
	"INVOICE_VALUE_INR" VARCHAR2(20 BYTE), 
	"CURRENCY" VARCHAR2(20 BYTE), 
	"MODEOF_TP_FEE" VARCHAR2(20 BYTE), 
	"REMARK" VARCHAR2(100 BYTE), 
	"SUB_LINE_NUMBER" VARCHAR2(20 BYTE), 
	"PORT_OF_DESTINATION" VARCHAR2(20 BYTE), 
	"PORT_OF_LOADING" VARCHAR2(20 BYTE), 
	"PORT_OF_DESCHARGED_CFS" VARCHAR2(20 BYTE), 
	"MULTIPAL_PAKAGES" VARCHAR2(20 BYTE), 
	"CBM" VARCHAR2(20 BYTE), 
	"HIGHT_VALUE" VARCHAR2(20 BYTE), 
	"GROS_WEIGHT" VARCHAR2(20 BYTE), 
	"UNIT" VARCHAR2(20 BYTE), 
	"VOLUME" VARCHAR2(20 BYTE), 
	"ITEM_NUMBER" VARCHAR2(10 BYTE), 
	"CARGO_MOVMNT" VARCHAR2(5 BYTE), 
	"DPD_CODE" VARCHAR2(20 BYTE), 
	"DPD_MOVEMENT" VARCHAR2(20 BYTE), 
	"DUTY_INR" VARCHAR2(20 BYTE), 
	"ROAD_CARR_CODE" VARCHAR2(20 BYTE), 
	"ROAD_TP_BOND_NO" VARCHAR2(20 BYTE), 
	"BL_TYPE" VARCHAR2(20 BYTE), 
	"NE_CARGO_MOVMNT" VARCHAR2(20 BYTE), 
	 PRIMARY KEY ("HBL_NO_PK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "VASDATA"  ENABLE, 
	 FOREIGN KEY ("MBL_NO_FK")
	  REFERENCES "VASAPPS"."IGM_BL_DETAILS" ("BL_NO_PK") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "VASDATA" ;


  GRANT DELETE ON "VASAPPS"."IGM_HBL_DETAILS" TO "VASAPPS_RW";
  GRANT INSERT ON "VASAPPS"."IGM_HBL_DETAILS" TO "VASAPPS_RW";
  GRANT SELECT ON "VASAPPS"."IGM_HBL_DETAILS" TO "VASAPPS_RW";
  GRANT UPDATE ON "VASAPPS"."IGM_HBL_DETAILS" TO "VASAPPS_RW";
  GRANT DELETE ON "VASAPPS"."IGM_HBL_DETAILS" TO "EDWAPPS";
  GRANT INSERT ON "VASAPPS"."IGM_HBL_DETAILS" TO "EDWAPPS";
  GRANT SELECT ON "VASAPPS"."IGM_HBL_DETAILS" TO "EDWAPPS";
  GRANT UPDATE ON "VASAPPS"."IGM_HBL_DETAILS" TO "EDWAPPS";
  GRANT SELECT ON "VASAPPS"."IGM_HBL_DETAILS" TO "VASAPPS_RO";
