
  CREATE TABLE "VASAPPS"."IGM_BL_DETAILS_PREVIOUS_DECLARATION_TWO" 
   (	"PK_BL_NO" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"PREVIOUS_DECLARATION" VARCHAR2(10 BYTE), 
	"SPLIT_INDICATOR" VARCHAR2(10 BYTE), 
	"CSN_NO" VARCHAR2(255 BYTE), 
	"CSN_DATE" VARCHAR2(255 BYTE), 
	"MCIN" VARCHAR2(255 BYTE), 
	"PCIN" VARCHAR2(255 BYTE), 
	 PRIMARY KEY ("PK_BL_NO") DISABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "VASDATA" ;
