create or replace PACKAGE RCL_IGM_FILE_INFO 
IS
    TYPE CONTAINER_CURSOR_REF IS REF CURSOR; 

 PROCEDURE RCL_IGM_ACK_FILE(
    P_O_REFIGMTABFIND  OUT  SYS_REFCURSOR, 
          P_I_V_BL            VARCHAR2 DEFAULT NULL,
          P_I_V_POD           VARCHAR2 DEFAULT NULL,
           P_I_V_VOYAGE       VARCHAR2 DEFAULT NULL,
          P_I_V_VESSEL       VARCHAR2 DEFAULT NULL,
          P_I_V_POD_TERMINAL   VARCHAR2 DEFAULT NULL,
          P_I_V_CONSIGNEE_COUNTRYCODE  VARCHAR2 DEFAULT NULL,
          P_I_V_CONSIGNEE_STATE  VARCHAR2 DEFAULT NULL,
        p_o_v_error        OUT  VARCHAR2 
); 

 PROCEDURE RCL_IGM_STOWAGE_IMPORT(
          P_O_REFIGMTABFIND  OUT  SYS_REFCURSOR,
            P_I_V_BL              VARCHAR2 DEFAULT NULL,
           P_I_V_CONTAINER_NUM  VARCHAR2 DEFAULT NULL,
           P_I_V_POD           VARCHAR2 DEFAULT NULL,
           P_I_V_VESSEL       VARCHAR2 DEFAULT NULL,
          P_I_V_VOYAGE       VARCHAR2 DEFAULT NULL,
          P_I_V_POD_TERMINAL   VARCHAR2 DEFAULT NULL,
          p_o_v_error        OUT  VARCHAR2 
); 

 PROCEDURE RCL_IGM_STOWAGE_EXPORT(
     P_O_REFIGMTABFIND  OUT  SYS_REFCURSOR,
            P_I_V_BL              VARCHAR2 DEFAULT NULL,
           P_I_V_CONTAINER_NUM  VARCHAR2 DEFAULT NULL,
           P_I_V_POL           VARCHAR2 DEFAULT NULL,
           P_I_V_VESSEL       VARCHAR2 DEFAULT NULL,
          P_I_V_VOYAGE       VARCHAR2 DEFAULT NULL,
          P_I_V_POL_TERMINAL   VARCHAR2 DEFAULT NULL,
          p_o_v_error        OUT  VARCHAR2 
); 

END RCL_IGM_FILE_INFO;